name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    with:
      python-version: "3.10"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mypy
    - name: Lint
      run: |
        pylint $(git ls-files '*.py')
    - name: Type Check
      run: |
        mypy src

